[package]
name = "sequitur-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = "1.0"
ahash = "0.8"

[dev-dependencies]
proptest = "1.0"
bolero = "0.11"
criterion = "0.5"

[[bench]]
name = "compression"
harness = false
